# fly.toml app configuration file generated for weathered-fire-9197 on 2023-06-29T09:25:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-fire-9197"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
